version: "3.5"
services:
  postgres:
    image: postgres
    container_name: fastify-slonik
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      docker_net:
        ipv4_address: 172.22.0.100
    volumes:
      - ./src/test/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  docker_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
