version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: test-postgres
    restart: "no"
    working_dir: /application
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_USER=test
    ports:
      - "5432:5432"
volumes:
  postgres:
    name: test-db
