name: Validate & Release
on:
  push:
    branches:
      - main
jobs:
  runner-job:
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432/postgres?sslmode=disable

    strategy:
      matrix:
        node-version: [14.x]

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
      - run: pnpm install
      - run: pnpm lint
      - run: docker-compose up -d
      - run: pnpm test

      - name: Semantic Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
